routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
/---------------------------------------------------------------------------------
/    Front-end route
/---------------------------------------------------------------------------------
*/
Route::group(['namespace' => 'Frontend'], function () {
     Route::get('/', 'HomeController@index')->name('frontend.home.index');
     //Route::get('product/','ProductController@show');
     Route::get('about', 'AcfController@about');
     Route::get('contact', 'AcfController@contact');
     Route::get('faqs', 'AcfController@faqs');
     Route::get('term', 'AcfController@term');
     Route::get('privacy', 'AcfController@privacy');
     Route::get('help', 'AcfController@help');


     // ***
     //
     // Product *******
     // 
     Route::get('shop', 'ProductController@shopIndex')->name('shop.index');
     Route::get('shop/PageAjax', 'ProductController@PageAjax');
     Route::get('s/filter', 'ProductController@shopFilter');
     Route::get('san-pham/{id}', 'ProductController@showProduct')->name('product.showProduct');
     Route::get('sp/filter', 'ProductController@filterPrice');
     Route::get('cat/pageAjax', 'ProductController@catPageAjax');

     //
     Route::get('san-pham/phan-trang/', 'ProductController@filterPrice');
     //
     // Category Load ***************
     //
     Route::get('/cat/{id}', 'ProductController@showProductFromCat');

     // Cart *************
     //
     Route::get('cart', 'CartController@index');
     Route::get('addToCard/{id}', 'CartController@getAddToCart')->name('cart.addTocCart');
     Route::get('getTotalQty', 'CartController@getTotalQty')->name('cart.getTotalQty');
     Route::post('cart/remove', 'CartController@getRemoveFromCart')->name('cart.getRemoveFromCart');
     Route::get('checkout', 'CartController@showCheckout');
     Route::post('doCheckout', 'CartController@doCheckout')->name('cart.doCheckout');
     Route::get('checkouted/{orderCode}', 'CartController@checkouted')->name('cart.checkouted');
     Route::get('order/', 'CartController@orderStatus')->name('doOrderSearch');
     Route::get('huy-bo-don-hang/{orderCode}', 'CartController@huyDonHang');

     Route::get('order-search', 'CartController@showOrderSearch');

     Route::post('minusA_Product', 'CartController@minusA_Product')->name('minusA_Product');
});
/*
/-----------------------------------------------------------------------------------
/    back-end route
/-----------------------------------------------------------------------------------
*/
Route::group(['namespace' => 'Backend'], function () {
     Route::get('login', 'LoginController@showLogin')->name('login');
     Route::post('login', 'LoginController@doLogin')->name('admin.doLogin');
     Route::post('logout', 'LoginController@logout')->name('dologout');
     Route::get('register', 'RegisterController@showReg');
     Route::post('register', 'RegisterController@doReg')->name('admin.doRegister');
});
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'middleware' => 'auth'], function () {


     Route::get('/', 'DashboardController@index');
     //->middleware('auth');
     // Category ********************************************************************************************
     //  
     // Index
     Route::resource('category', 'CategoryController');
     // load
     Route::get('category/get/ajax', 'CategoryController@list')->name('category.getData');
     // fetch data to form
     Route::get('category/get/fetchData', 'CategoryController@fetchData')->name('category.fetchData');
     // Delete A record
     Route::post('category/destroyACategory', 'CategoryController@destroyACategory')->name('category.destroyA');
     // Multi Destroy
     Route::post('category/multiDestroy', 'CategoryController@multiDestroy')->name('category.multiDestroy');
     // ******************************************************************************************************
     // Product **********************************************************************************************
     // 
     // Index 
     Route::resource('product', 'ProductController');
     // Load data
     Route::get('product/get/list', 'ProductController@getData')->name('product.getData');
     // Delete A record
     Route::post('product/destroyA', 'ProductController@destroyA')->name('product.destroyA');
     // Multi Destroy
     Route::post('product/multiDestroy', 'ProductController@multiDestroy')->name('product.multiDestroy');
     // show update image
     Route::get('update-image/{product}', 'ProductController@showUpdateImage');
     Route::post('do-update-image', 'ProductController@doUpdateImage')->name('doUpdateImage');
     Route::post('delete-image', 'ProductController@deleteImage')->name('deleteImage');
     Route::post('setActive', 'ProductController@setActive')->name('setActive');
     Route::post('setUnactive', 'ProductController@setUnactive')->name('setUnactive');
     // Test
     Route::get('product/get/aaa', 'ProductController@getDataA')->name('product.getDataA');

     // **************************************************************************************************
     // Order
     //
     // index
     Route::get('order', 'OrderController@index');
     // fetch Data 
     Route::get('getData', 'OrderController@getData')->name('order.getData');
     // Chấp nhận đơn hàng
     Route::post('acceptOrder', 'OrderController@acceptOrder')->name('acceptOrder');
     Route::post('deniedOrder', 'OrderController@deniedOrder')->name('deniedOrder');
     Route::get('update-order/{order}', 'OrderController@showUpdateOrder');
     Route::post('doUpdateOrder', 'OrderController@doUpdateOrder')->name('doUpdateOrder');
     Route::get('getOrderStatuses', 'OrderController@getOrderStatuses')->name('getOrderStatuses');
     Route::get('ajaxDeleteAOrderStatus', 'OrderController@ajaxDeleteAOrderStatus')->name('ajaxDeleteAOrderStatus');
});

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\backend\CategoryRequest;
use App\Models\Category;
use Datatables;
use Illuminate\Validation\Validator;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('backend.categories.index',['data'=>'index','type'=>'category']);

        // $categories = Category::paginate();
        // $page = $request->get('page');
        // return view('backend.categories.index')->with([
        //     'categories' => $categories,
        //     'page' => $page
        // ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.categories.create',['data'=>'create','type'=>'category']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        
        if ($request->get('button_action') == "insert") {
            // dd($request->all());
            $category = new Category([
                'name' => $request->get('categoryName'),
                'description' => $request->get('category-description'),
                'keyword' => $request->get('category_keyword')
            ]);
            $category->save();
            return response()->json([
                'status' => 'Thêm thành công !',
            ]);
        } else if ($request->get('button_action') == "update") {
            $category = Category::find($request->get('edit_category_id'));
            $category->name = $request->get('categoryName');
            $category->description = $request->get('category-description');
            $category->keyword = $request->get('category_keyword');
            $category->save();
            return response()->json([
                'status' => 'Cập nhật thành công !',
            ]);
        }
    }
    /** 
     * Fetch data to update
     * 
     */
    public function fetchData(
        Request $rq
    ) {
        $id = $rq->get('id');
        $category = Category::find($id);
        return response()->json([
            'id' => $id,
            'name' => $category->name,
            'description' => $category->description,
            'keyword' => $category->keyword
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function multiDestroy(Request $request)
    {
        $IDS = $request->id;
        Category::whereIn('id', $IDS)->delete();
        return response()->json([
            'return' => 'Xoá thành công ' . count($IDS) . ' bản ghi !',
        ]);
        // $rs = Category::whereIn('id',$IDS)->delete();
        // if($rs->delete()){
        //     echo "deleted";
        // }
    }

    public function destroyACategory(Request $request)
    {
        return response()->json([
            'status' => Category::destroy($request->id),
        ]);
    }

    public function list()
    {
        //$categogies = Category::all();
        $categogies = Category::query();
        return Datatables::of($categogies)
            ->make(true);

        // return response()->json([
        //     'CategoryPaginate' => $categogies,
        // ]);
        // $categogies = Category::paginate();
        // return response()->json([
        //     'CategoryPaginate'=>$categogies,
        // ]);
    }
    // public function list(){
    //     $categogies = Category::select('id', 'name','description','keyword');
    //     return Datatables::of($categogies)->make(true);
    //     // return response()->json([
    //     //     'CategoryPaginate'=>$categogies,
    //     // ]);
    // }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index(){
        $products= Product::all();
        $orderProducts = DB::table('order_product')
            ->join('orders', 'orders.id', '=', 'order_product.order_id')
            ->where('orders.status', 3)->get();
        return view('backend.dashboard.index', compact('products', 'orderProducts'));
    }
}

app/Http/Controllers/Backend/LoginController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    public function showLogin()
    {
        return view('backend.login');
    }
    public function doLogin(Request $request)
    {
        $credentials = $request->validate(
            [
                'email' => ['required', 'email'],
                'password' => ['required'],
            ],
            [
                'email.required' => 'Hãy nhập :attribute.',
                'email.email' => 'Hãy nhập đúng dạng email',
                'password.required',
            ],
            [
                'email' => 'Email',
                'password' => 'Mật khẩu',
            ]
        );

        if (Auth::attempt($credentials)) {
            // Authentication passed...
            return redirect('/admin');
        } else {
            return redirect()->back()->withErrors([
                'errorMsg' => 'Đăng nhập thất bại'
            ]);
        }
    }

    public function logout()
    {
        auth()->logout();
        return redirect('/login');
    }
}

app/Http/Controllers/Backend/RegisterController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RegisterController extends Controller
{
    public function showReg()
    {
        return view('backend.register');
    }
    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return \App\User
     */
    public function doReg(Request $request)
    {
        //return view('backend.auth.register');
        return User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
    }
}

app/Http/Controllers/Frontend/ProductController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Facades\Session;

class ProductController extends Controller
{

    public function shopIndex()
    {
        $session = Session::has('cart') ? Session::get('cart') : null;
        $allProducts = Product::all()->count();
        $products = Product::paginate(9);
        return view('frontend.product.shop', compact('session', 'products', 'allProducts'));
    }

    public function showProduct($id)
    {
        $product = Product::find($id);
        $session = Session::has('cart') ? Session::get('cart') : null;
        return view('frontend.product.showProduct', compact('product', 'session'));
    }

    public function showProductFromCat($id)
    {
        $session = Session::has('cart') ? Session::get('cart') : null;
        $category = Category::find($id);
        $products = $category->products()->orderBy('created_at', 'DESC')->paginate(9);
        $catId = $products[0]->category->id ?? null;
        $allProducts = $category->products->count();
        return view('frontend.product.shop', compact('session', 'products', 'allProducts', 'catId'));
    }

    public function filterPrice()
    {
        $filerProducts = Category::find(request()->id);
        $products = $filerProducts->products()->whereBetween('price', [request()->from, request()->to])
            ->paginate(9);
        if (request()->ajax()) {
            return response()->json([
                'html' => view('frontend.product.ajax_product', compact('products'))->render(),
            ]);
        }
    }

    public function PageAjax()
    {
        $products = Product::paginate(9);

        if (request()->ajax()) {
            return response()->json([
                'html' => view('frontend.product.ajax_product', compact('products'))->render(),
                'page' => request()->page,
            ]);
        }
    }

    public function shopFilter()
    {
        $products = Product::whereBetween('price', [request()->from, request()->to])
            ->paginate(9);

        if (request()->ajax()) {
            return response()->json([
                'html' => view('frontend.product.ajax_product', compact('products'))->render(),
            ]);
        }
    }

    public function catPageAjax()
    {
        $category = Category::find(request()->id);
        $products = $category->products()->orderBy('created_at', 'DESC')->paginate(9);

        if (request()->ajax()) {
            return response()->json([
                'html' => view('frontend.product.ajax_product', compact('products'))->render(),
                'page' => request()->page,
            ]);
        }
    }
}

resources/views/backend/products/create.blade.php
@extends('layouts.backend')
@section('css')
<link rel="stylesheet" href="{{ asset('backend/css/bootstrap-fileinput/css/fileinput.css') }}">
@endsection

@section('js')
<!-- CK Editor -->
<script src="{{ asset('plugins/ckeditor/ckeditor.js') }}"></script>
<script src="{{ asset('backend/css/bootstrap-fileinput/js/fileinput.js') }}"></script>
<script src="{{ asset('backend/css/bootstrap-fileinput/themes/fa/theme.js') }}"></script>
<script>
$(function() {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('description')
});
$('#image').fileinput({
    themes: 'fa',
    overwriteInitial: false,
    maxFileNum: 5,
});
</script>
@endsection

@section('content')
<div class="content-wrapper">
    @include('layouts.partions.backend.main-fixed.content.content_header_master')
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Thêm sản phẩm mới</h3>
                    </div>

                    <form id="data-form" action="{{ route('product.store') }}" method="post" class="form-horizontal"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="box-body">
                            <div class="form-group">
                                <label for="name" class="col-lg-2 col-sm-3 control-label">Tên sản phẩm</label>
                                <div class="col-lg-10 col-sm-9">
                                    <input type="text" name="name" id="name" class="form-control"
                                        placeholder="Nhập tên sản phẩm">

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror

                                </div>
                            </div>

                            <div class="form-group">
                                <label for="price" class="col-lg-2 col-sm-3 control-label">Tên giá sản phẩm</label>
                                <div class="col-lg-10 col-sm-9">
                                    <input type="number" name="price" id="price" class="form-control"
                                        placeholder="Nhập giá sản phẩm">

                                    @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror

                                </div>
                            </div>

                            <div class="form-group">
                                <label for="qty" class="col-lg-2 col-sm-3 control-label">Số lượng</label>
                                <div class="col-lg-10 col-sm-9">
                                    <input type="number" name="qty" id="qty" class="form-control"
                                        placeholder="Số lượng">

                                    @error('qty')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror

                                </div>
                            </div>

                            <div class="form-group">
                                <label for="image" class="col-lg-2 col-sm-3 control-label">Ảnh</label>
                                <div class="col-lg-10 col-sm-9">
                                    <input id="image" name="image[]" type="file" class="file" multiple
                                        data-show-upload="false" data-show-caption="true" data-show-preview="false"
                                        data-msg-placeholder="Chọn ảnh...">
                                    @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="category_id" class="col-lg-2 col-sm-3 control-label">Mã loại danh
                                    mục</label>
                                <div class="col-lg-10 col-sm-9">
                                    <select name="category_id" id="category_id" class="select_category_id">
                                        <option value="-1">Chọn một danh mục</option>
                                        @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('category_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                            </div>


                            <div class="form-group">
                                <label for="keyword" class="col-lg-2 col-sm-3 control-label">Key Word</label>
                                <div class="col-lg-10 col-sm-9">
                                    <textarea name="keyword" id="keyword" rows="3" class="form-control"></textarea>
                                    @error('keyword')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="keyword" class="col-lg-2 col-sm-3 control-label">Mô tả</label>
                                <!-- /.box-header -->
                                <div class="col-lg-10 col-sm-9">
                                    <textarea id="description" name="description" rows="10" cols="80"></textarea>
                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                        </div>
                        
                        <div class="box-footer" style="text-align:center">
                            <a href="/admin/product" class="btn btn-default" style="margin:0px 15px">Trở lại</a>
                            <button type="submit" class="btn btn-info" onclick="event.preventDefault();
                                                     document.getElementById('data-form').submit();">Thêm</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/backend/products/imagesIndexAjaxContent.blade.php
@foreach($product->productimages as $image)
<div class="col-lg-2 col-sm-6 image-box">
    <div class="image-box-container {{ $image->status == 1 ? 'active' : '' }}">
        <div class="image-box-header">
            <div class="checkbox checkbox-success">
                <input id="checkbox3" class="styled" type="checkbox" data-id="{{ $image->id }}">
                <label>
                </label>
            </div>
            <a href="javascript:void(0);" 
                class="btn btn-social-icon btn-default _view-image" 
                style="margin-right: 5px"
                data-src="/storage/{{ $image->image }}"><i class="fas fa-eye"></i></a>
            <a href="javascript:void(0);" 
                class="btn btn-social-icon btn-google _delete-image"
                data-id="{{ $image->id }}"
                ><i class="fas fa-trash-alt"></i></a>
        </div>
        <div class="image-box-body">
            <img src="/storage/{{ $image->image }}" alt="{{ $image->alt }}">
        </div>
    </div>
</div>
@endforeach

resources/views/backend/products/index.blade.php
@extends('layouts.backend')
@section('content')
<div class="content-wrapper">
    @include('layouts.partions.backend.main-fixed.content.content_header_master')
    @include('layouts.partions.backend.main-fixed.content.product.mainContent')
</div>
@endsection
@section('css')
<link rel="stylesheet" href="{{ asset('backend/css/dataTable/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('backend/css/dataTable/select.dataTables.min.css') }}">
<link rel="stylesheet" type='text/css' href="{{ asset('backend/css/dataTable/dataTables.checkboxes.css') }}">
<link rel="stylesheet" type='text/css' href="{{ asset('backend/css/dataTable/awesome-bootstrap-checkbox.css') }}">
@endsection

@section('js')
<script type="text/javascript" src="{{ asset('backend/js/dataTable/jquery.dataTables.js') }}"></script>
<script type="text/javascript" src="{{ asset('backend/js/dataTable/dataTables.bootstrap4.js') }}"></script>
<script type="text/javascript" src="{{ asset('backend/js/dataTable/dataTables.select.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('backend/js/dataTable/dataTables.checkboxes.js') }}"></script>
<script type="text/javascript" src="{{ asset('backend/js/product_func.js') }}"></script>
<script>
    // Form validation
    $(document).ready(function() {
        $.validate({
            form: '#_create-form'
        });
        $('#productDescription').restrictLength($('#des-max-length'));
        $('#productKeyword').restrictLength($('#keyword-max-length'));

        // Gọi hàm load dữ liệu ra bảng
        //
        LoadDataTable();
    });
</script>
@endsection